<template>
  <div class="page">
    <div class="page-head"><div><h2>订单管理</h2><p class="muted">订单、明细和库存变化均保存到 MySQL。</p></div><el-button type="primary" @click="openCreate">＋ 创建订单</el-button></div>
    <section class="panel filters"><el-input v-model="filters.orderNo" clearable placeholder="搜索订单号"/><el-select v-model="filters.status" clearable placeholder="全部状态"><el-option label="已创建" value="CREATED"/><el-option label="已完成" value="COMPLETED"/><el-option label="已取消" value="CANCELLED"/></el-select><el-button type="primary" @click="search">查询</el-button></section>
    <section class="panel"><el-table :data="result.records" v-loading="loading"><el-table-column prop="orderNo" label="订单号" min-width="190"/><el-table-column prop="customerName" label="客户"/><el-table-column label="金额"><template #default="{row}">¥{{money(row.totalAmount)}}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="tagType(row.status)">{{statusText(row.status)}}</el-tag></template></el-table-column><el-table-column prop="createTime" label="创建时间" min-width="180"/><el-table-column label="操作" width="210"><template #default="{row}"><el-button text @click="showDetail(row.id)">详情</el-button><el-button v-if="row.status==='CREATED'" text type="success" @click="finish(row)">完成</el-button><el-button v-if="row.status==='CREATED'" text type="danger" @click="cancel(row)">取消</el-button></template></el-table-column></el-table><el-pagination class="pager" background layout="total,prev,pager,next" :total="result.total" :page-size="filters.size" v-model:current-page="filters.page" @current-change="load"/></section>
    <el-dialog v-model="visible" title="创建订单" width="700px"><el-form label-position="top"><div class="form-grid"><el-form-item label="客户名称"><el-input v-model="form.customerName"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.customerPhone"/></el-form-item></div><el-form-item label="订单商品"><div class="items"><div v-for="(item,index) in form.items" :key="index" class="item"><el-select v-model="item.dessertId"><el-option v-for="d in desserts" :key="d.id" :label="`${d.name} · ¥${money(d.price)} · 库存 ${d.stock}`" :value="d.id" :disabled="d.status!==1"/></el-select><el-input-number v-model="item.quantity" :min="1" :precision="0"/><el-button text type="danger" @click="form.items.splice(index,1)">删除</el-button></div><el-button @click="form.items.push({dessertId:null,quantity:1})">＋ 添加商品</el-button></div></el-form-item><el-form-item label="备注"><el-input v-model="form.remark"/></el-form-item><div class="total">预计金额：<strong>¥{{money(estimated)}}</strong><small>最终金额以后端数据库为准</small></div></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">创建</el-button></template></el-dialog>
    <el-drawer v-model="drawer" title="订单详情" size="540px"><template v-if="detail"><h3>{{detail.orderNo}} · {{statusText(detail.status)}}</h3><p>{{detail.customerName}}　¥{{money(detail.totalAmount)}}</p><el-table :data="detail.items"><el-table-column prop="dessertName" label="甜品"/><el-table-column prop="quantity" label="数量"/><el-table-column label="小计"><template #default="{row}">¥{{money(row.subtotal)}}</template></el-table-column></el-table></template></el-drawer>
  </div>
</template>
<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {pageDesserts} from '../api/dessert'
import {pageOrders,getOrder,createOrder,completeOrder,cancelOrder} from '../api/order'
const result=reactive({records:[],total:0}),filters=reactive({page:1,size:10,orderNo:'',status:''}),form=reactive({customerName:'',customerPhone:'',remark:'',items:[]})
const desserts=ref([]),loading=ref(false),saving=ref(false),visible=ref(false),drawer=ref(false),detail=ref(null)
const money=v=>Number(v||0).toFixed(2),statusText=v=>({CREATED:'已创建',COMPLETED:'已完成',CANCELLED:'已取消'}[v]||v),tagType=v=>({CREATED:'warning',COMPLETED:'success',CANCELLED:'info'}[v]||'')
const estimated=computed(()=>form.items.reduce((sum,x)=>sum+Number(desserts.value.find(d=>d.id===x.dessertId)?.price||0)*x.quantity,0))
async function load(){loading.value=true;try{Object.assign(result,await pageOrders(filters))}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
function search(){filters.page=1;load()} function openCreate(){Object.assign(form,{customerName:'',customerPhone:'',remark:'',items:[{dessertId:null,quantity:1}]});visible.value=true}
async function save(){if(!form.customerName.trim()||form.items.some(x=>!x.dessertId)){ElMessage.warning('请填写客户并选择商品');return}saving.value=true;try{await createOrder(form);ElMessage.success('订单创建成功');visible.value=false;await load()}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
async function showDetail(id){detail.value=await getOrder(id);drawer.value=true}
async function finish(row){try{await ElMessageBox.confirm(`确认完成 ${row.orderNo}？`);await completeOrder(row.id);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}}
async function cancel(row){try{await ElMessageBox.confirm('取消后将自动返还库存，是否继续？','取消订单',{type:'warning'});await cancelOrder(row.id);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}}
onMounted(async()=>{desserts.value=(await pageDesserts({page:1,size:100})).records;await load()})
</script>
<style scoped>.filters{display:grid;grid-template-columns:2fr 1fr auto;gap:12px}.pager{justify-content:flex-end;margin-top:18px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.items{width:100%}.item{display:grid;grid-template-columns:1fr 130px auto;gap:10px;margin-bottom:10px}.item .el-select{width:100%}.total{padding:14px;background:var(--surface-2);border-radius:12px}.total strong{color:var(--amber-strong);font-size:22px}.total small{float:right;color:var(--muted)}@media(max-width:700px){.filters,.form-grid,.item{grid-template-columns:1fr}}</style>
